/* Fidelio
 *
 * (c) 2026 Daniele Lacamera <root@danielinux.net>
 *
 *
 * Fidelio is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * Fidelio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1335, USA
 *
 */

/* Per-device attestation identity.
 *
 * The attestation key used to be a static array in src/cert.c, generated by
 * mkcert.sh at build time: one key for the whole firmware, identical on every
 * unit flashed with the same image, sitting in unprotected flash with no
 * secure boot in front of it. Extracting it from a single device - or reading
 * the build machine - forged built-in attestations for every unit of that
 * build.
 *
 * It is now derived from the PUF master secret, the same root the credential
 * keys come from, so it never leaves the device and is unique per unit. The
 * self-signed certificate that carries its public key is built on demand and
 * cached in RAM; the cache is bound to the secret it came from, so a reset
 * that re-derives that secret in place gets a fresh certificate rather than a
 * stale one. Nothing about the certificate needs to be stable across power
 * cycles, so it costs no flash and no wear.
 *
 * This is still basic (self-signed) attestation: no relying party has this
 * key on a CA list, so the certificate remains unverifiable to them. What is
 * restored is that the attestation is per device, and that one extraction no
 * longer covers the fleet.
 */

#ifndef FIDELIO_ATT_H
#define FIDELIO_ATT_H

#include <stdint.h>
#include "wolfssl/wolfcrypt/settings.h"
#include "wolfssl/wolfcrypt/ecc.h"
#include "wolfssl/wolfcrypt/random.h"

/* Initialise `key` with this device's attestation key. On success the caller
 * owns it and must wc_ecc_free() it; on failure `key` is left zeroed, which
 * is also safe to pass to wc_ecc_free(), so callers with a single cleanup
 * path do not need to special-case the error. Returns 0 on success, -1
 * otherwise.
 */
int att_key_init(ecc_key *key);

/* Hand back this device's self-signed attestation certificate in DER. It is
 * generated and signed (one P-256 signature, ~116 ms at 125 MHz) on the first
 * call and again whenever the master secret has changed since; otherwise the
 * cached copy is returned. `rng` must be initialised. Returns 0 on success,
 * -1 otherwise.
 */
int att_cert_get(WC_RNG *rng, const uint8_t **der, uint32_t *der_len);

#endif /* FIDELIO_ATT_H */
